### ISSUE TITLE
Unknown command "Chaos"

### ISSUE THREAD

**Issue by 54234123** [Pinsplash/halflife2chaos#87] opened 2024-01-16 15:59 UTC
**Describe the bug**
Every hl2chaos console command doesnt work.

**To Reproduce**
1. Download and install hl2chaos with source sdk 2013 singleplayer.
2. Set source sdk 2013 singleplayer to upcoming in options.
3. Copy bin folder from steamapps\common\Source SDK Base 2013 Singleplayer\sourcetest and Paste it to sourcemods\hl2chaos
4. Copy hl2 maps from steamapps\common\Half-Life 2\hl2\maps and paste it to sourcemods\hl2chaos\maps.

**Expected behavior**
"The game should work as intended"

Note: I tried to make hl2 chaos work by installing source sdk 2007 but it still doesnt work.
![I love hl2chaos](https://github.com/Pinsplash/halflife2chaos/assets/156825092/e8099989-282f-4a4e-881b-567f22eed027)

**Comment by acuifex** [comment] 2024-01-16 16:13
Sounds like a duplicate of this: https://github.com/Pinsplash/halflife2chaos/issues/34#issuecomment-1522307095

**Comment by 54234123** [comment] 2024-01-16 18:01
I already tried it and it stil doesnt work.

**Comment by 54234123** [comment] 2024-01-20 21:13
Okay nevermind i forgot to copy all of the hl2chaos files from the releases tab to my game files.

**Closed** 2024-01-20 21:13 UTC
